application: thegiggliography
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /mystyle.css
  static_files: mystyle.css
  upload: mystyle.css

- url: /images
  static_dir: images

- url: /scripts
  static_dir: scripts

- url: .*
  static_files: index.html
  upload: index.html

libraries:
- name: webapp2
  version: "2.5.2"
